language: node_js
sudo: false
dist: trusty
node_js:
- 7
- 6
cache:
  yarn: true
  directories:
    - node_modules
script: yarn run test:single
after_success:
- cat coverage/lcov.info | ./node_modules/.bin/codecov
